DROP TABLE IF EXISTS TYPES cascade;
CREATE TABLE TYPES
(
    TYPE_ID  LONG AUTO_INCREMENT NOT NULL,
    TYPE_NAME  VARCHAR(100)         NOT NULL,
    PRIMARY KEY (TYPE_ID)
);

DROP TABLE IF EXISTS THEMES cascade;
CREATE TABLE THEMES
(
    THEME_ID  LONG AUTO_INCREMENT NOT NULL,
    THEME_NAME  VARCHAR(100)         NOT NULL,
    PRIMARY KEY (THEME_ID)
);


DROP TABLE IF EXISTS PUBLISHERS cascade;
CREATE TABLE PUBLISHERS
(
    PUBLISHER_ID  LONG AUTO_INCREMENT NOT NULL,
    PUBLISHER_NAME  VARCHAR(100)         NOT NULL,
    PRIMARY KEY (PUBLISHER_ID)
);

DROP TABLE IF EXISTS AUTHORS cascade;
CREATE TABLE AUTHORS
(
    AUTHOR_ID  LONG AUTO_INCREMENT NOT NULL,
--     AUTHOR_NO  INTEGER             NOT NULL,
    LAST_NAME  VARCHAR(30)         NOT NULL,
    FIRST_NAME VARCHAR(30),
    PATRONOMIC VARCHAR(30),
    PRIMARY KEY (AUTHOR_ID)
);

DROP TABLE IF EXISTS PUBLICATIONS cascade;
CREATE TABLE PUBLICATIONS
(
    PUBLICATION_ID      LONG AUTO_INCREMENT NOT NULL,
    DATE_OF_PUBLICATION DATE,
    PUBLICATION_NAME    VARCHAR(40)        NOT NULL,
    PAGE_COUNT          INTEGER             NOT NULL
);

DROP TABLE IF EXISTS PUBLICATION_TYPE cascade;
CREATE TABLE PUBLICATION_TYPE
(
    PUBLICATION_ID LONG,
    TYPE_ID      LONG,
    PRIMARY KEY (PUBLICATION_ID, TYPE_ID),
    CONSTRAINT PUBLICATION_TYPE_ID_FK
        FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATIONS (PUBLICATION_ID),
    CONSTRAINT TYPE_ID_FK
        FOREIGN KEY (TYPE_ID)
            REFERENCES TYPES (TYPE_ID)
);

DROP TABLE IF EXISTS PUBLICATION_THEME cascade;
CREATE TABLE PUBLICATION_THEME
(
    PUBLICATION_ID LONG,
    THEME_ID      LONG,
    PRIMARY KEY (PUBLICATION_ID, THEME_ID),
    CONSTRAINT PUBLICATION_THEME_ID_FK
        FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATIONS (PUBLICATION_ID),
    CONSTRAINT THEME_ID_FK
        FOREIGN KEY (THEME_ID)
            REFERENCES THEMES (THEME_ID)
);


DROP TABLE IF EXISTS PUBLICATION_PUBLISHER cascade;
CREATE TABLE PUBLICATION_PUBLISHER
(
    PUBLICATION_ID LONG,
    PUBLISHER_ID      LONG,
    PRIMARY KEY (PUBLICATION_ID, PUBLISHER_ID),
    CONSTRAINT PUBLICATION_PUBLISHER_ID_FK
        FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATIONS (PUBLICATION_ID),
    CONSTRAINT PUBLISHER_ID_FK
        FOREIGN KEY (PUBLISHER_ID)
            REFERENCES PUBLISHERS (PUBLISHER_ID)
);

DROP TABLE IF EXISTS PUBLICATION_AUTHOR cascade;
CREATE TABLE PUBLICATION_AUTHOR
(
    PUBLICATION_ID LONG,
    AUTHOR_ID      LONG,
    PRIMARY KEY (PUBLICATION_ID, AUTHOR_ID),
    CONSTRAINT PUBLICATION_AUTHOR_ID_FK
        FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATIONS (PUBLICATION_ID),
    CONSTRAINT AUTHOR_ID_FK
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES AUTHORS (AUTHOR_ID)
);

